/*
** File usbwall_mod.c for project usbwall
**
** Made by David FERNANDES
** Login   <dfernand@ece.fr>
**
** Started on  Mon Dec  19 9:17:29 2011 David FERNANDES
**
** Copyright (C) 2012 - David FERNANDES
**
** This program is free software; you can redistribute it and/or
** modify it under the terms of the GNU Lesser General Public License
** as published by the Free Software Foundation; either version 2
** of the License, or (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/
/*
** \file usbwall_mod.c
**
** module for USB mass-storage device filtering
** Detailed documentation
** On multiple lines...
**
** \author David FERNANDES
**
*/

/*** Headers ***/
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/errno.h>
#include <linux/usb.h>
#include "storage.h"
#include "trace.h"

MODULE_AUTHOR("David FERNANDES");
MODULE_DESCRIPTION("Module for USB mass-storage device filtering");
MODULE_LICENSE("GPL");

/*** Storage class code : Mass storage ***/
#define USB_CLASS_MASS_STORAGE 8

/*** Variables temporary used : white liste ***/
#define VENDOR_ID_MY_KEY_4GO 0x1970
#define PRODUCT_ID_MY_KEY_4GO 0x0000
/* #define SERIAL_NUMBER_MY_KEY_4GO 0x3E462902115024271106 */

/*** Devices supported by the module : All mass storage ***/
static struct usb_device_id usbwall_id_table [] = {

   /* Typically, flash devices : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_RBC, USB_PR_DEVICE) },

   /* CD-ROM : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8020, USB_PR_DEVICE) },

   /* QIC-157 Tapes  : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_QIC, USB_PR_DEVICE) },

   /* Floppy : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_UFI, USB_PR_DEVICE) },

   /* Removable media : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_8070, USB_PR_DEVICE) },

   /* Transparent media : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_SCSI, USB_PR_DEVICE) },

   /* Password-protected  : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_KARMA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_LOCKABLE, USB_PR_DEVICE) },

   /* 	ISD200 ATA : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, USB_SC_ISD200, USB_PR_DEVICE) },

   /* Cypress ATACB : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_CYP_ATACB, USB_PR_DEVICE) },

   /* Use device's value : all storage protocol */  
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_CBI) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_CB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_BULK) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_UAS) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_USBAT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_EUSB_SDDR09) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_SDDR55) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_DPCM_USB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_FREECOM) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_DATAFAB) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_JUMPSHOT) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_ALAUDA) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_KARMA ) },
   { USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE,	USB_SC_DEVICE, USB_PR_DEVICE) },

   { }
};
MODULE_DEVICE_TABLE (usb, usbwall_id_table);

/*** kernel's representation of a USB device ***/
static struct usb_device * dev;

static int usbwall_open(struct inode *inode, struct file *file)
{
  DBG_TRACE("the device is not on the white liste");
  return 0;
  /* return -EPERM; */
}

/*** Function called by the kernel when a device is detected ***/
static int usbwall_probe(struct usb_interface *intf, const struct usb_device_id *devid)
{
  DBG_TRACE("entering in the function probe");
  
  dev = interface_to_usbdev (intf);
  /* Research if the device is on the white list*/
  /* If the device is on the white liste : the module is released */ 
  if(dev->descriptor.idProduct == PRODUCT_ID_MY_KEY_4GO && 
     dev->descriptor.idVendor == VENDOR_ID_MY_KEY_4GO  
     /* && dev->descriptor.iSerialNumber == SERIAL_NUMBER_MY_KEY_4GO */
  ){
    DBG_TRACE("the device is on the white liste");
  }
  /* Else : creation a fake device */
  else
  {
    DBG_TRACE("the device is not on the white liste");
    DBG_TRACE("its idVendor is %x", dev->descriptor.idVendor);
    DBG_TRACE("its idProduct is %x", dev->descriptor.idProduct);
    /* DBG_TRACE("its SerialNumber is %x", dev->descriptor.iSerialNumber); */
    /* return -EPERM; */
  }
  return 0;
}

static void usbwall_disconnect(struct usb_interface *intf)
{
  printk("Module_usbwall : device disconnected"); 
}

static const struct file_operations usbwall_operations = {
  .open =         usbwall_open,
};

static struct usb_driver usbwall_driver = {
  .name = "usbwall",
  .probe = usbwall_probe,
  .disconnect = usbwall_disconnect,
  .id_table = usbwall_id_table,
};
 
/*** Loading the module ***/
static int __init usbwall_init(void)      
{ 
  int usbwall_register;
  usbwall_register = 0;
  usbwall_register = usb_register(&usbwall_driver);
  if(usbwall_register)
  {
     DBG_TRACE("register failed, error : %d",usbwall_register);
  } 
  DBG_TRACE("module loaded"); 
  return usbwall_register; 
}

/*** Unloading the module ***/
static void __exit usbwall_exit(void)
{
  usb_deregister(&usbwall_driver);
  DBG_TRACE("module unloaded"); 
}

module_init (usbwall_init);
module_exit (usbwall_exit);
