#
# Makefile for Project usbwall in .
#
# Made by David Fernandes
# Login   <dfernand@ece.fr>
#
# Started on  Tue Jan  10 14:49:06 2012 David FERNANDES
# 

all :
	gcc load_white_list.c -o load_white_list

clean :
	rm load_white_list
     
